#!/bin/bash
### BEGIN INIT INFO
# Provides:          colbp-server
# Required-Start:    $remote_fs $network
# Required-Stop:     $remote_fs $network
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: colbp data structure server
### END INIT INFO

do_start()
{
    cd /usr/local/dpcs/
    ./colbp
}

do_stop()
{
    ID = `ps -ef|grep colbp |grep -v grep| awk '{print $2}'`
    for id in $ID
    do
        sudo kill -9 $id
        echo "kill $id"
    done
}

case "$1" in
start)
    do_start
    ;;
stop)
    do_stop
    ;;
restart)
    do_stop
    do_start
    ;;
**)
    echo "error $1"
    ;;
esac
