#!/bin/sh
#程序卸载时执行，删除相关关联文件之前执行

echo "delete dpcs"

sudo systemctl stop colbp
sudo systemctl stop dpcs

sudo systemctl disable colbp
sudo systemctl disable dpcs

#sudo rm /etc/systemd/system/colbp.service /etc/systemd/system/dpcs.service
#sudo rm /etc/init.d/dpcs /etc/init.d/colbp

sudo systemctl daemon-reload

sudo ufw delete allow dpcs
sudo rm -rf /usr/local/dpcs
echo "Remove finished"