#!/bin/sh
#程序卸载时执行，删除相关关联文件之前执行

echo "delete dpcs"

sudo systemctl stop dpcs

sudo systemctl disable dpcs

sudo rm /etc/systemd/system/dpcs.service

sudo rm /etc/init.d/dpcs

sudo systemctl daemon-reload

sudo ufw delete allow dpcs