#!/bin/sh
#程序安装完成时执行，一般用于配置执行环境 位于DEBIAN文件夹中，安装处理文件，在解包后执行

echo "install dpcs !"

sudo mv /usr/local/dpcs/tmp/dpcs.service /etc/systemd/system/
sudo mv /usr/local/dpcs/tmp/colbp.service /etc/systemd/system/
sudo mv /usr/local/dpcs/tmp/dpcs /etc/init.d/
sudo mv /usr/local/dpcs/tmp/colbp /etc/init.d/


sudo chmod 644 /etc/systemd/system/dpcs.service
sudo chmod 644 /etc/systemd/system/colbp.service

sudo chmod 777 /etc/init.d/dpcs
sudo chmod 777 /etc/init.d/colbp

sudo mkdir -p /usr/local/dpcs/var
sudo chown amplesky:amplesky -R /usr/local/dpcs
sudo chown amplesky:amplesky -R /usr/local/dpcs/var

sudo ufw allow dpcs

sudo systemctl daemon-reload

sudo systemctl enable colbp.service

sudo systemctl enable dpcs.service

sudo service dpcs start
sudo service colbp start
echo "DPCS install finished"
